apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: container-apps-edocv2
        image: deden7/testing:1.0
        ports:
        - containerPort: 3000
          name: pathao-port
          protocol: TCP
      imagePullSecrets:
      - name: docker-registry
